### ISSUE TITLE
Evaluate potential website ideas

### ISSUE THREAD

**Issue by UA92-Devops-Apprentices** [UA92-Devops-Apprentices/DevNexus#1]

**Comment by UA92-Devops-Apprentices** [comment]
# IDEA #1 - E-Learning Platform
This platform would provide courses to users for them to complete on a self directed basis, below is a screenshot of what this sort of project might look like

## Benefits
- Heavily data driven, likely require working with a relational database AND document, providing added challenge
- Would need user auth, allowing us to implement that as well
- Extensible. We can start simple and develop features further as we progress.
- Easy to analyze. We have access to multiple e-learning platforms ourselves and can use our own knowledge of how they work to critique them and improve ours
- Multiple approaches possible

![Image](https://github.com/UA92-Devops-Apprentices/Project-2/assets/134611926/df748cf1-7351-4a45-aaca-d72ca7ae446e)


## MVP
- Clear Courses, easy to use website
-

**Comment by Apollo-XIV** [comment]
We're doing e-learning
