### ISSUE TITLE
Picking a Cloud Provider

### ISSUE THREAD

**Issue by UA92-Devops-Apprentices** [UA92-Devops-Apprentices/DevNexus#2]
- [x] Determine Minimum Spec and rough scaling metric
- [x] Find cost for minimum spec in each of primary candidates
- - [ ] Azure
- - [ ] AWS
- - [ ] GCP

We need to decide which cloud provider to use, based on a few of the following factors:
- **Cost**. For a basic implementation of the service how much will it cost per month across the platforms
- **Ease of Use**. How much time will be taken away by having to use a more complex service
- **Other Factors**. This encompasses less traditional benefits such as free tiers, existing credits, and lab environments.

## Optional: Multi-Cloud
Choosing a multi-cloud environment can provide added benefits at the expense of added complexity.

**Comment by UA92-Devops-Apprentices** [comment]
# Primary Candidates
**Azure**
**AWS**
**GCP**

**Comment by UA92-Devops-Apprentices** [comment]
# Minimum Spec
The metrics for the service are based on a t2.micro EC2 Instance.

- VM: 1vCPU, 1GBi RAM
- Object Storage: 1GB
- Database Volume: 2GB

# Scaling
To scale, assume horizontal scaling for the VM, creating more instances rather than choosing a larger one. For data storage, for each added VM add one GB of storage p/m

**Comment by Apollo-XIV** [comment]
AWS seems to be final, need to do:
- [x] cost analysis
- [x] redundancy & SLAs
- [x] Regions and Storage <- GDPR

**Comment by Apollo-XIV** [comment]
[My Estimate - AWS Pricing Calculator.pdf](https://github.com/UA92-Devops-Apprentices/DevNexus/files/11625892/My.Estimate.-.AWS.Pricing.Calculator.pdf)

£8.92p/m - EC2 t3.micro

**Comment by Apollo-XIV** [comment]
![Image](https://github.com/UA92-Devops-Apprentices/DevNexus/assets/119538960/f35d869e-5120-4055-ab51-9cf38a7bfd2d)
Here are the SLAs for EC2s on AWS. For redundancy we'd do well to have try and make sure our data is backed up, in the event of failure.

**Comment by Apollo-XIV** [comment]
We're planning to use the eu-west regions (London and Ireland). We could use these both as fault tolerant zones or just pick whichever is cheapest. Ireland is a popular choice. For the sakes of GDPR, we will only be using servers in countries that observer and comply with GDPR, and we'll have a relatively simple privacy policy that explains exactly what GDPR precautions we've taken. We'll be able to better determine these considerations once we better understand our data needs and what data we'll be storing directly and what we'll be handling.
