### ISSUE TITLE
Identify Stakeholders

### ISSUE THREAD

**Issue by UA92-Devops-Apprentices** [UA92-Devops-Apprentices/DevNexus#3]
We need to create a client for ourselves, this can take the form of a company or client that has requested the service. With this, we can identify some basic capabilities our end-product will need.

- [x] Identify Client
- [ ] Identify Key Capabilities

**Comment by Apollo-XIV** [comment]
Client - We're a startup making an E-learning platform for novices, hobbyists, and young professionals. Our site aims to open the doors to tech and help users enter the space and broaden their knowledge.
